import assert from 'node:assert/strict';
import { test } from 'node:test';
import { mkdtempSync, writeFileSync, readFileSync, rmSync, mkdirSync } from 'node:fs';
import path from 'node:path';
import { tmpdir } from 'node:os';
import pg from 'pg';
import { chromium } from 'playwright';
import { runMigrations } from '../../lib/server/db/migrate.ts';
import { closePools, getAppPool } from '../../lib/server/db/pool.ts';
import { loadCuratedCatalog } from '../../lib/server/catalog/store.ts';
import { FIXTURE_CURATION_MANIFEST } from '../../lib/server/catalog/fixture-manifest.ts';
import { EXA_SEARCH_URL } from '../../lib/server/discovery/exa-search.ts';
import type { EvaluationRunView } from '../../lib/api/atlas-client.ts';
import { eventually, startProcess, stopProcess, startTestApp, seedSession, FRONTEND } from '../support/discovery-browser.ts';

test('DP04 main brief → durable Exa proposals → worker restart → closed tab reopened', {timeout:180000}, async t=> {
  assert.ok(process.env.GROWTHX_ADMIN_DATABASE_URL,'isolated database required');
  const admin=new pg.Client({connectionString:process.env.GROWTHX_ADMIN_DATABASE_URL});await admin.connect();await runMigrations();
  const tenant=await seedSession(admin),decoy=await seedSession(admin);
  await loadCuratedCatalog(getAppPool(),tenant.tenantId,structuredClone(FIXTURE_CURATION_MANIFEST));
  const temp=mkdtempSync(path.join(tmpdir(),'dp04-transport-'));const fixture=path.join(temp,'transport.json'),calls=path.join(temp,'calls.log');
  writeFileSync(fixture,JSON.stringify({[EXA_SEARCH_URL]:{body:JSON.stringify({requestId:'controlled',costDollars:{total:.007},results:[{url:'https://lu.ma/dp04-source',title:'A source to investigate',text:'A partial search excerpt.'},{url:'https://luma.com/dp04-source?utm_source=test',title:'Same page alias'}]}),contentType:'application/json'}}));
  const app=await startTestApp();const browser=await chromium.launch({headless:true});
  const workers:ReturnType<typeof startProcess>[]=[];
  t.after(async()=>{await browser.close();for(const w of workers)await stopProcess(w.child);await app.close();await closePools();await admin.end();rmSync(temp,{recursive:true,force:true});});
  const context=await browser.newContext({viewport:{width:1366,height:900}});await context.addCookies([{name:'growthx_session',value:tenant.token,url:app.base,httpOnly:true}]);
  const page=await context.newPage();const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(app.base);await page.getByTestId('research-coverage').waitFor();await page.getByRole('navigation').getByRole('button',{name:'Brief',exact:true}).click();
  await page.getByLabel('Product',{exact:true}).fill('Agent observability');await page.getByLabel('Audience',{exact:true}).fill('Backend developers');
  await page.getByRole('button',{name:'Adoption',exact:true}).click();
  await page.getByRole('button',{name:'Review brief',exact:true}).click();
  const request=page.waitForRequest(r=>r.url().endsWith('/api/evaluations')&&r.method()==='POST');
  await page.getByRole('button',{name:'Confirm and research SF'}).click();assert.equal((await request).postDataJSON().researchScope,'sf_discovery');
  const runId=await eventually(async()=>new URL(page.url()).searchParams.get('run'),'accepted run');
  const read=async():Promise<EvaluationRunView>=>{const r=await context.request.get(`${app.base}/api/evaluations/${runId}`);assert.equal(r.status(),200);return r.json();};
  const first=startProcess(['worker/index.ts'],FRONTEND,{GROWTHX_WORKER_EXA_FIXTURE:fixture,GROWTHX_WORKER_EXA_CALLS_FILE:calls,GROWTHX_WORKER_EXIT_AFTER_STEP:'discover_sources'});workers.push(first);
  await eventually(async()=>first.child.exitCode!==null?true:null,'worker stopped after durable discovery');
  assert.equal(first.child.exitCode,0,first.log());const partial=await read();assert.equal(partial.steps.find(s=>s.name==='discover_sources')?.state,'completed');assert.notEqual(partial.state,'completed');
  assert.equal(partial.discovery!.candidates.length,1);assert.equal(partial.discovery!.sources.length,6);
  await page.close();const reopened=await context.newPage();await reopened.goto(`${app.base}/?run=${runId}`);await reopened.getByTestId('discovery-candidate').waitFor();
  assert.equal(await reopened.locator('[data-organizer-id]').count(),0,'existing fixtures never fill discovery');
  const ids=await reopened.getByTestId('discovery-candidate').getAttribute('data-source-ids');
  const second=startProcess(['worker/index.ts'],FRONTEND,{GROWTHX_WORKER_EXA_FIXTURE:fixture,GROWTHX_WORKER_EXA_CALLS_FILE:calls,GROWTHX_WORKER_EXIT_AFTER_STEP:''});workers.push(second);
  await eventually(async()=> (await read()).state==='completed'?true:null,'run resumed');
  assert.equal(readFileSync(calls,'utf8').trim().split('\n').length,3,'restart made no repeated call');
  await reopened.reload();await reopened.getByTestId('discovery-candidate').waitFor();assert.equal(await reopened.getByTestId('discovery-candidate').getAttribute('data-source-ids'),ids);
  await reopened.getByTestId('discovery-audit').locator('summary').click();assert.match(await reopened.getByTestId('discovery-audit').innerText(),/USD 0.021/);
  const directory=process.env.GROWTHX_E2E_SCREENSHOT_DIR;
  if(directory){mkdirSync(directory,{recursive:true});await reopened.screenshot({path:path.join(directory,'discovery-desktop.png'),fullPage:true,animations:'disabled'});}
  await reopened.setViewportSize({width:390,height:844});assert.ok(await reopened.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1));
  if(directory)await reopened.screenshot({path:path.join(directory,'discovery-mobile.png'),fullPage:true,animations:'disabled'});
  const other=await browser.newContext();await other.addCookies([{name:'growthx_session',value:decoy.token,url:app.base}]);assert.equal((await other.request.get(`${app.base}/api/evaluations/${runId}`)).status(),404);
  await reopened.getByRole('navigation').getByRole('button',{name:'Events',exact:true}).click();assert.equal(await reopened.getByTestId('sf-edition-list').locator('[data-edition-id]').count(),0);
  assert.deepEqual(errors,[]);
  t.diagnostic('Unmodified primary request, Exa fixture explicitly synthetic, 3 attempts persisted, worker process stopped/restarted, same source IDs after tab closure, no fixture organizer fallback, 404 cross tenant, desktop/mobile.');
});
