import assert from 'node:assert/strict';
import {test} from 'node:test';
import {randomUUID} from 'node:crypto';
import {mkdirSync,writeFileSync} from 'node:fs';
import path from 'node:path';
import pg from 'pg';
import {chromium} from 'playwright';
import {runMigrations} from '../../lib/server/db/migrate.ts';
import {loadCuratedCatalog} from '../../lib/server/catalog/store.ts';
import {createEvaluationService} from '../../lib/server/evaluations/service.ts';
import {stopEvaluationQueue} from '../../lib/server/evaluations/queue.ts';
import {closePools} from '../../lib/server/db/pool.ts';
import {comparisonFixture} from '../fixtures/comparison.ts';
import {briefBody} from '../fixtures/research-brief.ts';
import type {ComparisonRunResult} from '../../lib/server/evaluations/compare.ts';
function comparisonResult(run: {result: unknown} | null): ComparisonRunResult | null {return (run?.result as ComparisonRunResult) ?? null;}
import {FRONTEND,startTestApp,startProcess,stopProcess,seedSession,eventually} from '../support/source-browser.ts';

test('DP07 production browser: select two -> inspect pinned antecedent -> edit brief -> differences -> reopen unchanged',{timeout:180000},async t=>{
 assert.ok(process.env.GROWTHX_ADMIN_DATABASE_URL&&!process.env.GROWTHX_ADMIN_DATABASE_URL.includes(':54329/'),'Isolated DB required');
 await runMigrations();const admin=new pg.Client({connectionString:process.env.GROWTHX_ADMIN_DATABASE_URL});await admin.connect();const session=await seedSession(admin);
 const appPool=new pg.Pool({connectionString:process.env.GROWTHX_DATABASE_URL});const fixture=comparisonFixture();await loadCuratedCatalog(appPool,session.tenantId,fixture.manifest);
 const service=createEvaluationService();const app=await startTestApp();const worker=startProcess(['worker/index.ts'],FRONTEND);const browser=await chromium.launch();
 t.after(async()=>{await browser.close();await stopProcess(worker.child);await app.close();await stopEvaluationQueue();await closePools();await appPool.end();await admin.end();});
 const base=await service.accept({...session,body:{...briefBody(),idempotencyKey:randomUUID()}});if(base.status!=='accepted')throw Error('profile');
 await eventually(async()=> (await service.getRun({tenantId:session.tenantId,runId:base.runId}))?.state==='completed'?true:null,'profile completed');
 const context=await browser.newContext({viewport:{width:1366,height:900}});await context.addCookies([{name:'growthx_session',value:session.token,url:app.base,httpOnly:true}]);const page=await context.newPage();const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(app.base);await page.addStyleTag({content:'.research-main{scroll-behavior:auto!important}'});await page.getByRole('navigation').getByRole('button',{name:'Events',exact:true}).click();
 const list=page.getByTestId('sf-edition-list');
 for(const id of [fixture.ait.editionId,fixture.vultr.editionId])await list.locator(`[data-edition-id="${id}"]`).getByRole('checkbox').check();
 const accepted=page.waitForResponse(r=>r.url().endsWith('/api/evaluations')&&r.request().method()==='POST');await page.getByRole('button',{name:'Compare selected (2/3)'}).click();const response=await accepted;assert.equal(response.status(),202);const runId=(await response.json()).runId;
 const panel=page.getByTestId('comparison-panel');await panel.waitFor();await page.getByTestId('research-priority').waitFor();assert.match(await page.getByTestId('research-priority').innerText(),/Explore.*Agents, Everywhere/);
 const original=comparisonResult(await service.getRun({tenantId:session.tenantId,runId}));assert.ok(original);const originalJson=JSON.stringify(original.bundle);
 const ait=panel.locator(`article[data-edition-id="${fixture.ait.editionId}"]`);assert.match(await ait.getByTestId('alternative-reading').innerText(),/Budget incomplete/); await ait.getByText('Background, proposed activity and cost',{exact:true}).click();
 await ait.getByText('View background evidence',{exact:true}).click();assert.match(await ait.innerText(),/Monitoring, auditing, and recovery/);
 const dir=process.env.GROWTHX_E2E_SCREENSHOT_DIR??'/tmp/dp07-browser';mkdirSync(dir,{recursive:true});await page.screenshot({path:path.join(dir,'comparison-evidence.png'),fullPage:true,animations:'disabled'});
 await page.getByTestId('research-priority').getByRole('heading').evaluate(el=>el.scrollIntoView({block:'start',behavior:'instant'}));await page.screenshot({path:path.join(dir,'comparison-desktop.png'),fullPage:true,animations:'disabled'});
 const historyId=original.bundle.editions.find(e=>e.name.includes('Secure Agents'))!.editionId;
 await ait.getByRole('button',{name:/Secure Agents.*saved revision/}).click();const dossier=page.getByTestId('edition-dossier');await dossier.waitFor();assert.equal(await dossier.getAttribute('data-edition-id'),historyId);assert.equal(await dossier.getAttribute('data-edition-revision-id'),original.bundle.editions.find(e=>e.editionId===historyId)!.id);
 await page.goto(`${app.base}/?run=${runId}`);await panel.waitFor();await page.getByTestId('comparison-brief-editor').locator('summary').click();
 await page.getByLabel('Comparison product',{exact:true}).fill('Pagos para comercios');await page.getByLabel('Comparison audience',{exact:true}).fill('Equipos de pagos');await page.getByLabel('Comparison stack',{exact:true}).fill('');await page.getByLabel('Comparison goal',{exact:true}).selectOption('hiring');
 await page.getByLabel('Comparison budget',{exact:true}).fill('200');await page.getByLabel('Comparison currency',{exact:true}).fill('EUR');await page.getByLabel('Comparison constraints',{exact:true}).fill('Solo contactos con opt-in\nNo comprar listas');
 await page.getByLabel('Comparison start date',{exact:true}).fill('2026-09-20');await page.getByLabel('Comparison end date',{exact:true}).fill('2026-10-30');
 const revisedResponse=page.waitForResponse(r=>r.url().endsWith('/api/evaluations')&&r.request().method()==='POST');await page.getByRole('button',{name:'Create evaluation with this brief',exact:true}).click();const revised=await revisedResponse;assert.equal(revised.status(),202);const revisedRunId=(await revised.json()).runId;
 await page.getByTestId('comparison-differences').waitFor(); await page.getByTestId('comparison-differences').locator('summary').click();assert.match(await page.getByTestId('research-priority').innerText(),/No option has enough relevant evidence/);assert.match(await page.getByTestId('comparison-differences').innerText(),/Pagos para comercios/);assert.match(await page.getByTestId('comparison-differences').innerText(),/No comprar listas/);
 const revisedBundle=comparisonResult(await service.getRun({tenantId:session.tenantId,runId:revisedRunId}))!.bundle;assert.deepEqual(revisedBundle.profile.window,{from:'2026-09-20',to:'2026-10-30'});assert.deepEqual(revisedBundle.profile.stack,[]);assert.equal(revisedBundle.snapshot.alternatives.find(a=>a.editionId===fixture.ait.editionId)!.eligibility.status,'excluded');
 await page.getByTestId('comparison-differences').getByRole('heading').evaluate(el=>el.scrollIntoView({block:'start',behavior:'instant'}));
 await page.screenshot({path:path.join(dir,'comparison-differences.png'),fullPage:true,animations:'disabled'});
 await page.setViewportSize({width:390,height:844});await page.getByTestId('alternative-reading').first().scrollIntoViewIfNeeded();await page.screenshot({path:path.join(dir,'comparison-mobile.png'),fullPage:true,animations:'disabled'});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'no horizontal overflow');
 await page.goto(`${app.base}/?run=${runId}`);await panel.waitFor();assert.match(await page.getByTestId('research-priority').innerText(),/Explore/);assert.deepEqual(JSON.stringify(comparisonResult(await service.getRun({tenantId:session.tenantId,runId}))!.bundle),originalJson);assert.deepEqual(errors,[]);
 writeFileSync(path.join(dir,'../controlled-browser.json'),JSON.stringify({material:'controlled synthetic evidence; real PostgreSQL, worker and production browser',runId,revisedRunId,snapshotId:original.snapshotId,checks:{twoAlternatives:true,antecedentFragment:true,pinnedDossier:true,briefEdit:true,differences:true,mobileNoOverflow:true,reopenedUnchanged:true},errors},null,2));
});
