import assert from 'node:assert/strict';
import {test} from 'node:test';
import {randomUUID} from 'node:crypto';
import {mkdtempSync,writeFileSync,readFileSync,rmSync,mkdirSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
import pg from 'pg';
import {chromium} from 'playwright';
import {runMigrations} from '../../lib/server/db/migrate.ts';
import {stopEvaluationQueue} from '../../lib/server/evaluations/queue.ts';
import {closePools} from '../../lib/server/db/pool.ts';
import {createEvaluationService} from '../../lib/server/evaluations/service.ts';
import {briefBody} from '../fixtures/research-brief.ts';
import {richSourceHtml,RICH_SOURCE_URL} from '../fixtures/source-reading.ts';
import {FRONTEND,startTestApp,startProcess,stopProcess,seedSession,eventually} from '../support/source-browser.ts';

test('DP-05 browser: import rich source, inspect fragments and conflict, reload and read on mobile',{timeout:180000},async t=>{
  assert.ok(process.env.GROWTHX_ADMIN_DATABASE_URL && !process.env.GROWTHX_ADMIN_DATABASE_URL.includes(':54329/'),'Explicit isolated DB required; shared localhost:54329 is prohibited');
  for(const key of ['EXA_API_KEY','APIFY_TOKEN','GEMINI_API_KEY'])delete process.env[key];
  const admin=new pg.Client({connectionString:process.env.GROWTHX_ADMIN_DATABASE_URL});await admin.connect();await runMigrations();
  const tenant=await seedSession(admin),decoy=await seedSession(admin);
  const temp=mkdtempSync(path.join(tmpdir(),'dp05-transport-'));const fixture=path.join(temp,'transport.json'),calls=path.join(temp,'calls.log');
  writeFileSync(fixture,JSON.stringify({[RICH_SOURCE_URL]:{body:richSourceHtml()}}));
  const app=await startTestApp();const browser=await chromium.launch({headless:true});
  const worker=startProcess(['worker/index.ts'],FRONTEND,{GROWTHX_WORKER_LUMA_FIXTURE:fixture,GROWTHX_WORKER_LUMA_CALLS_FILE:calls});
  t.after(async()=>{await browser.close();await stopProcess(worker.child);await app.close();await stopEvaluationQueue();await closePools();await admin.end();rmSync(temp,{recursive:true,force:true});});
  const service=createEvaluationService();const base=await service.accept({tenantId:tenant.tenantId,userId:tenant.userId,body:{...briefBody(),idempotencyKey:randomUUID()}});assert.equal(base.status,'accepted');
  const baseId=(base as {runId:string}).runId;
  await eventually(async()=> (await service.getRun({tenantId:tenant.tenantId,runId:baseId}))?.state==='completed'?true:null,'base research completed');
  const context=await browser.newContext({viewport:{width:1366,height:900}});await context.addCookies([{name:'growthx_session',value:tenant.token,url:app.base,httpOnly:true}]);
  const page=await context.newPage();const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(`${app.base}/?run=${baseId}`);await page.getByTestId('run-progress').waitFor();
  await page.getByRole('navigation').getByRole('button',{name:'Events',exact:true}).click();
  await page.getByLabel('Luma event URL').fill(RICH_SOURCE_URL);
  const acceptance=page.waitForResponse(r=>r.url().endsWith('/api/events/ingest')&&r.request().method()==='POST');
  await page.getByRole('button',{name:'Import',exact:true}).click();assert.equal((await acceptance).status(),202);
  const runId=await eventually(async()=>{const id=new URL(page.url()).searchParams.get('run');return id&&id!==baseId?id:null;},'ingest URL');
  await page.getByRole('button',{name:'Open saved dossier'}).waitFor({timeout:60000});
  await page.getByRole('button',{name:'Open saved dossier'}).click();
  const dossier=page.getByTestId('edition-dossier');await dossier.waitFor();
  for(const label of ['Audience','Announced sponsors','Public address','Date']) await dossier.locator('.research-fact').filter({has:page.getByText(label,{exact:true})}).getByTestId('claim-evidence').locator('summary').click();
  const text=await dossier.innerText();
  assert.match(text,/Announced sponsors/i);assert.match(text,/Wasmer/);assert.match(text,/Tenki/);assert.match(text,/agent builders/);assert.match(text,/94105/);assert.match(text,/contradicted/);assert.match(text,/April 21, 2027/);assert.match(text,/2027-04-20/);assert.match(text,/HTML line/);assert.match(text,/automatically extracted; not human verified|without human verification/);
  const id=await dossier.getAttribute('data-edition-id'),revision=await dossier.getAttribute('data-edition-revision-id');assert.ok(id&&revision);
  const dir=process.env.GROWTHX_E2E_SCREENSHOT_DIR;
  if(dir){mkdirSync(dir,{recursive:true});await page.screenshot({path:path.join(dir,'reading-desktop.png'),fullPage:true,animations:'disabled'});const sponsors=dossier.locator('.research-fact').filter({has:page.getByText('Announced sponsors',{exact:true})});await sponsors.screenshot({path:path.join(dir,'reading-sponsors.png')});}
  await page.reload();await page.getByRole('button',{name:'Open saved dossier'}).click();await dossier.waitFor();assert.equal(await dossier.getAttribute('data-edition-id'),id);assert.equal(await dossier.getAttribute('data-edition-revision-id'),revision);
  assert.equal(readFileSync(calls,'utf8').trim().split('\n').length,1,'reload uses persisted reading, not another request');
  await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
  const mobileAudience=dossier.locator('.research-fact').filter({has:page.getByText('Audience',{exact:true})});
  await mobileAudience.getByTestId('claim-evidence').locator('summary').click();await mobileAudience.scrollIntoViewIfNeeded();
  if(dir)await page.screenshot({path:path.join(dir,'reading-mobile.png'),fullPage:true,animations:'disabled'});
  const other=await browser.newContext();await other.addCookies([{name:'growthx_session',value:decoy.token,url:app.base}]);assert.equal((await other.request.get(`${app.base}/api/catalog/editions/${id}`)).status(),404);assert.equal((await other.request.get(`${app.base}/api/evaluations/${runId}`)).status(),404);
  assert.deepEqual(errors,[]);
  t.diagnostic('Controlled HTML; real PostgreSQL, queue, worker, Next and Chromium. Audience/sponsor/address fragments, both dates, same revision after reload, tenant 404 and no mobile overflow. No paid providers.');
});
