// Manifiesto de curación SINTÉTICO y etiquetado (ticket 09).
//
// Demuestra el mecanismo de carga interna explícita y el recorrido del dossier
// sin acreditar NINGÚN evento real: la DECISIÓN ABIERTA D4 (URLs reales,
// responsable de verificación, material conservable) sigue pendiente y este
// material lleva material: 'synthetic' en la carga y en la lectura. Lo usan la
// prueba de integración (curated-dossier.test.ts) y la carga de demo
// (scripts/load-curated-catalog.ts --fixture).
//
// El contenido está construido para ejercitar los criterios del ticket:
// - Dos organizadores comparables con un antecedente documentado cada uno
//   (Berlín conserva su geografía: es antecedente, no oportunidad local).
// - Dos homónimos con identidades separadas; un coorganizador que no hereda
//   los eventos ajenos ni la trayectoria del otro.
// - Audiencia con dos fuentes que discrepan (revisión contradicha que conserva
//   la revisión anterior), costo pendiente y acceso pendiente.
// - Participación de empresa con rol pagado REPORTADO (con fuente) y resultado
//   comercial desconocido, y un logo presente que no se promociona a
//   patrocinio ni a resultados.
// - Una edición con soporte solo a nivel país (sin ciudad ni punto de mapa).

import type { CurationManifest } from './manifest.ts';

const VERIFIED_AT = '2026-09-08T00:00:00Z';
const REVIEWER = 'Curaduría sintética (fixture de CI)';

export const FIXTURE_MANIFEST_NAME = 'catalogo-sf-fixture-sintetico';

export const FIXTURE_CURATION_MANIFEST: CurationManifest = {
  manifestVersion: '1',
  name: FIXTURE_MANIFEST_NAME,
  material: 'synthetic',
  authorizedBy: REVIEWER,
  verifiedAt: VERIFIED_AT,
  note:
    'Material sintético etiquetado: demuestra el mecanismo de catálogo curado y NO acredita la revisión de eventos reales (D4 pendiente).',
  sources: [
    {
      contractVersion: '1',
      id: 'src-luma-dev-summit',
      url: 'https://luma.example/sf-dev-summit-2027',
      locator: 'sección «About this event»',
      provider: 'luma (synthetic)',
      collector: 'growthx-curation',
      fetchedAt: VERIFIED_AT,
      publishedAt: '2026-08-15',
      method: 'manual_curation',
      geoScope: 'city',
      content: {
        kind: 'excerpt',
        excerpt:
          'SF Dev Summit — March 10, 2027 · Mission District, San Francisco. Registration open.',
      },
      usageRestrictions: ['extracto breve con fines de evaluación; no republicar la página completa'],
    },
    {
      contractVersion: '1',
      id: 'src-organizer-site-a',
      url: 'https://baybuilders.example/2027',
      locator: 'landing del evento',
      provider: 'sitio del organizador (synthetic)',
      collector: 'growthx-curation',
      fetchedAt: VERIFIED_AT,
      publishedAt: '2026-08-20',
      method: 'manual_curation',
      geoScope: 'city',
      content: { kind: 'excerpt', excerpt: 'Esperamos 150 builders de AI e infraestructura.' },
      usageRestrictions: [],
    },
    {
      contractVersion: '1',
      id: 'src-community-report',
      url: 'https://sfdevnotes.example/expectativas-2027',
      locator: 'párrafo 3',
      provider: 'newsletter comunitaria (synthetic)',
      collector: 'growthx-curation',
      fetchedAt: VERIFIED_AT,
      publishedAt: '2026-09-01',
      method: 'manual_curation',
      geoScope: 'city',
      content: { kind: 'excerpt', excerpt: 'Las últimas ediciones convocaron cerca de 60 asistentes.' },
      usageRestrictions: [],
    },
    {
      contractVersion: '1',
      id: 'src-recap-berlin',
      url: 'https://baybuilders.example/berlin-2025-recap',
      locator: null,
      provider: 'blog del organizador (synthetic)',
      collector: 'growthx-curation',
      fetchedAt: VERIFIED_AT,
      publishedAt: '2025-11-20',
      method: 'manual_curation',
      geoScope: 'city',
      content: { kind: 'hash', sha256: '2f1f9f3f0000000000000000000000000000000000000000000000000000beef' },
      usageRestrictions: ['solo hash: el recap completo no se conserva'],
    },
    {
      contractVersion: '1',
      id: 'src-sponsor-page',
      url: 'https://quiverlabs.example/events',
      locator: 'entrada «Berlin 2025»',
      provider: 'sitio del sponsor (synthetic)',
      collector: 'growthx-curation',
      fetchedAt: VERIFIED_AT,
      publishedAt: '2025-10-01',
      method: 'manual_curation',
      geoScope: 'city',
      content: { kind: 'excerpt', excerpt: 'Quiver Labs patrocina el track de agentes en Berlín.' },
      usageRestrictions: [],
    },
    {
      contractVersion: '1',
      id: 'src-logo-wall',
      url: 'https://ggml.example/2025-photos',
      locator: 'foto del muro de sponsors',
      provider: 'galería del evento (synthetic)',
      collector: 'growthx-curation',
      fetchedAt: VERIFIED_AT,
      publishedAt: null,
      method: 'manual_curation',
      geoScope: 'city',
      content: { kind: 'none' },
      usageRestrictions: [],
    },
    {
      contractVersion: '1',
      id: 'src-luma-ml-night',
      url: 'https://luma.example/gg-ml-night-oct',
      locator: null,
      provider: 'luma (synthetic)',
      collector: 'growthx-curation',
      fetchedAt: VERIFIED_AT,
      publishedAt: '2026-08-30',
      method: 'manual_curation',
      geoScope: 'city',
      content: { kind: 'excerpt', excerpt: 'GG ML Night — October 1, 2026, San Francisco.' },
      usageRestrictions: [],
    },
    {
      contractVersion: '1',
      id: 'src-organizer-site-b',
      url: 'https://ggml.example/about',
      locator: null,
      provider: 'sitio del organizador (synthetic)',
      collector: 'growthx-curation',
      fetchedAt: VERIFIED_AT,
      publishedAt: null,
      method: 'manual_curation',
      geoScope: 'city',
      content: { kind: 'excerpt', excerpt: 'Meetups de ML y data para gente de Python.' },
      usageRestrictions: [],
    },
    {
      contractVersion: '1',
      id: 'src-recap-sf-2025',
      url: 'https://ggml.example/junio-2025-recap',
      locator: null,
      provider: 'blog del organizador (synthetic)',
      collector: 'growthx-curation',
      fetchedAt: VERIFIED_AT,
      publishedAt: '2025-06-20',
      method: 'manual_curation',
      geoScope: 'city',
      content: { kind: 'excerpt', excerpt: 'La edición de junio en SoMa cerró con demos de la comunidad.' },
      usageRestrictions: [],
    },
  ],
  companies: [
    { contractVersion: '1', id: 'comp-quiverlabs', name: 'Quiver Labs (synthetic)', websiteUrl: 'https://quiverlabs.example' },
    { contractVersion: '1', id: 'comp-nimbusdb', name: 'NimbusDB (synthetic)', websiteUrl: null },
  ],
  organizers: [
    {
      contractVersion: '1',
      id: 'org-bay-builders-r1',
      organizerId: 'org-bay-builders',
      displayName: 'Bay Builders Collective (synthetic)',
      aliases: [{ alias: 'BayBuilders SF', confirmation: 'proposed', sourceIds: [] }],
      claimRevisionIds: ['clm-bay-focus-r1'],
      revisedAt: VERIFIED_AT,
      previousRevisionId: null,
    },
    {
      contractVersion: '1',
      id: 'org-gg-ml-r1',
      organizerId: 'org-gg-ml',
      displayName: 'Golden Gate ML Circle (synthetic)',
      aliases: [],
      claimRevisionIds: ['clm-gg-focus-r1'],
      revisedAt: VERIFIED_AT,
      previousRevisionId: null,
    },
    // Homónimos deliberados: mismo displayName, identidades SEPARADAS.
    {
      contractVersion: '1',
      id: 'org-mission-ai-a-r1',
      organizerId: 'org-mission-ai-a',
      displayName: 'Mission AI Collective (synthetic)',
      aliases: [],
      claimRevisionIds: [],
      revisedAt: VERIFIED_AT,
      previousRevisionId: null,
    },
    {
      contractVersion: '1',
      id: 'org-mission-ai-b-r1',
      organizerId: 'org-mission-ai-b',
      displayName: 'Mission AI Collective (synthetic)',
      aliases: [],
      claimRevisionIds: [],
      revisedAt: VERIFIED_AT,
      previousRevisionId: null,
    },
  ],
  editions: [
    {
      contractVersion: '1',
      id: 'ed-sf-dev-summit-2027-r1',
      editionId: 'ed-sf-dev-summit-2027',
      // Coorganización explícita: org-mission-ai-b participa de ESTA edición y
      // no hereda los antecedentes de org-bay-builders.
      organizerIds: ['org-bay-builders', 'org-mission-ai-b'],
      name: 'SF Dev Summit 2027 (synthetic)',
      canonicalUrl: 'https://luma.example/sf-dev-summit-2027',
      provider: 'luma',
      startDate: { precision: 'instant', iso: '2027-03-10T18:00:00-08:00', timezone: 'America/Los_Angeles' },
      location: { scope: 'city', name: 'San Francisco' },
      coordinates: { lat: 37.7599, lng: -122.4148 },
      claimRevisionIds: [
        'clm-summit-date-r1',
        'clm-summit-loc-r1',
        'clm-summit-aud-r1',
        'clm-summit-cost-r1',
        'clm-summit-access-r1',
      ],
      revisedAt: VERIFIED_AT,
      previousRevisionId: null,
    },
    {
      contractVersion: '1',
      id: 'ed-ml-night-2026-r1',
      editionId: 'ed-ml-night-2026',
      organizerIds: ['org-gg-ml'],
      name: 'GG ML Night (synthetic)',
      canonicalUrl: 'https://luma.example/gg-ml-night-oct',
      provider: 'luma',
      // Día sin zona declarada: la vigencia se evalúa bajo el rango real de
      // offsets (política del ticket 04) y cambia con el reloj controlado.
      startDate: { precision: 'date_only', date: '2026-10-01', timezone: null },
      location: { scope: 'city', name: 'San Francisco' },
      coordinates: { lat: 37.7936, lng: -122.3986 },
      claimRevisionIds: ['clm-mlnight-access-r1'],
      revisedAt: VERIFIED_AT,
      previousRevisionId: null,
    },
    {
      contractVersion: '1',
      id: 'ed-builders-berlin-2025-r1',
      editionId: 'ed-builders-berlin-2025',
      organizerIds: ['org-bay-builders'],
      name: 'Builders Night Berlin 2025 (synthetic)',
      canonicalUrl: 'https://baybuilders.example/berlin-2025',
      provider: null,
      startDate: { precision: 'instant', iso: '2025-11-15T18:00:00+01:00', timezone: 'Europe/Berlin' },
      // Antecedente FUERA de SF: conserva su geografía y jamás aparece como
      // oportunidad futura local.
      location: { scope: 'city', name: 'Berlin' },
      coordinates: { lat: 52.52, lng: 13.405 },
      claimRevisionIds: [],
      revisedAt: VERIFIED_AT,
      previousRevisionId: null,
    },
    {
      contractVersion: '1',
      id: 'ed-gg-ml-2025-r1',
      editionId: 'ed-gg-ml-2025',
      organizerIds: ['org-gg-ml'],
      name: 'GG ML Night junio 2025 (synthetic)',
      canonicalUrl: 'https://ggml.example/junio-2025',
      provider: null,
      startDate: { precision: 'instant', iso: '2025-06-12T18:00:00-07:00', timezone: 'America/Los_Angeles' },
      location: { scope: 'city', name: 'San Francisco' },
      coordinates: { lat: 37.7786, lng: -122.3893 },
      claimRevisionIds: [],
      revisedAt: VERIFIED_AT,
      previousRevisionId: null,
    },
    {
      contractVersion: '1',
      id: 'ed-us-roadshow-2027-r1',
      editionId: 'ed-us-roadshow-2027',
      organizerIds: ['org-gg-ml'],
      name: 'US Builders Roadshow 2027 (synthetic)',
      canonicalUrl: null,
      provider: null,
      startDate: { precision: 'date_only', date: '2027-05-01', timezone: null },
      // Soporte solo a nivel país: sin ciudad y SIN punto en el mapa (el
      // contrato rechaza coordenadas con este alcance).
      location: { scope: 'country', name: 'United States' },
      coordinates: null,
      claimRevisionIds: [],
      revisedAt: VERIFIED_AT,
      previousRevisionId: null,
    },
  ],
  participations: [
    {
      contractVersion: '1',
      id: 'part-quiver-berlin-r1',
      participationId: 'part-quiver-berlin',
      companyId: 'comp-quiverlabs',
      editionId: 'ed-builders-berlin-2025',
      role: 'paid_sponsor',
      roleStatus: 'reported',
      sourceIds: ['src-sponsor-page'],
      announcedDetail: 'Anunciada como sponsor del track de agentes.',
      reportedExecution: 'El recap reporta el booth operativo ambos días.',
      // Resultado comercial DESCONOCIDO: «no publicado» no equivale a fracaso.
      commercialOutcome: { status: 'unknown' },
      revisedAt: VERIFIED_AT,
      previousRevisionId: null,
    },
    {
      contractVersion: '1',
      id: 'part-nimbus-ggml-r1',
      participationId: 'part-nimbus-ggml',
      companyId: 'comp-nimbusdb',
      editionId: 'ed-gg-ml-2025',
      // Rol ambiguo documentado como lo que es: un logo presente, sin
      // patrocinio pagado inferido ni resultados atribuidos.
      role: 'logo_present',
      roleStatus: 'observed',
      sourceIds: ['src-logo-wall'],
      announcedDetail: null,
      reportedExecution: null,
      commercialOutcome: { status: 'unknown' },
      revisedAt: VERIFIED_AT,
      previousRevisionId: null,
    },
  ],
  claims: [
    {
      contractVersion: '1',
      id: 'clm-bay-focus-r1',
      claimId: 'clm-bay-focus',
      subject: { type: 'organizer', organizerId: 'org-bay-builders' },
      attribute: 'focus',
      value: { kind: 'text', text: 'ai, agents, python, devtools' },
      status: 'announced',
      sourceIds: ['src-organizer-site-a'],
      method: 'manual_curation',
      note: null,
      reviewer: REVIEWER,
      reviewedAt: VERIFIED_AT,
      previousRevisionId: null,
    },
    {
      contractVersion: '1',
      id: 'clm-gg-focus-r1',
      claimId: 'clm-gg-focus',
      subject: { type: 'organizer', organizerId: 'org-gg-ml' },
      attribute: 'focus',
      value: { kind: 'text', text: 'ml, data, python' },
      status: 'announced',
      sourceIds: ['src-organizer-site-b'],
      method: 'manual_curation',
      note: null,
      reviewer: REVIEWER,
      reviewedAt: VERIFIED_AT,
      previousRevisionId: null,
    },
    {
      contractVersion: '1',
      id: 'clm-summit-date-r1',
      claimId: 'clm-summit-date',
      subject: { type: 'edition', editionId: 'ed-sf-dev-summit-2027' },
      attribute: 'date',
      value: {
        kind: 'date',
        date: { precision: 'instant', iso: '2027-03-10T18:00:00-08:00', timezone: 'America/Los_Angeles' },
      },
      status: 'observed',
      sourceIds: ['src-luma-dev-summit'],
      method: 'manual_curation',
      note: null,
      reviewer: REVIEWER,
      reviewedAt: VERIFIED_AT,
      previousRevisionId: null,
    },
    {
      contractVersion: '1',
      id: 'clm-summit-loc-r1',
      claimId: 'clm-summit-loc',
      subject: { type: 'edition', editionId: 'ed-sf-dev-summit-2027' },
      attribute: 'location',
      value: { kind: 'location', scope: 'city', name: 'San Francisco (Mission District)' },
      status: 'observed',
      sourceIds: ['src-luma-dev-summit'],
      method: 'manual_curation',
      note: null,
      reviewer: REVIEWER,
      reviewedAt: VERIFIED_AT,
      previousRevisionId: null,
    },
    {
      contractVersion: '1',
      id: 'clm-summit-aud-r1',
      claimId: 'clm-summit-aud',
      subject: { type: 'edition', editionId: 'ed-sf-dev-summit-2027' },
      attribute: 'audience',
      // Lo que respalda la página: una EXPECTATIVA publicada de 150, no 150
      // asistentes reales.
      value: { kind: 'number', amount: 150, unit: 'asistentes anunciados' },
      status: 'announced',
      sourceIds: ['src-organizer-site-a'],
      method: 'manual_curation',
      note: null,
      reviewer: REVIEWER,
      reviewedAt: VERIFIED_AT,
      previousRevisionId: null,
    },
    {
      contractVersion: '1',
      id: 'clm-summit-aud-r2',
      claimId: 'clm-summit-aud',
      subject: { type: 'edition', editionId: 'ed-sf-dev-summit-2027' },
      attribute: 'audience',
      value: { kind: 'number', amount: 150, unit: 'asistentes anunciados' },
      // Dos fuentes discrepan: la contradicción es una revisión NUEVA que
      // conserva la anterior y nombra qué contradice a qué.
      status: 'contradicted',
      sourceIds: ['src-organizer-site-a', 'src-community-report'],
      method: 'manual_curation',
      note: 'El sitio del organizador anuncia 150 asistentes; el reporte comunitario estima ~60. Discrepancia sin resolver.',
      reviewer: REVIEWER,
      reviewedAt: '2026-09-08T00:10:00Z',
      previousRevisionId: 'clm-summit-aud-r1',
    },
    {
      contractVersion: '1',
      id: 'clm-summit-cost-r1',
      claimId: 'clm-summit-cost',
      subject: { type: 'edition', editionId: 'ed-sf-dev-summit-2027' },
      attribute: 'cost:sponsorship',
      value: { kind: 'pending', note: 'partidas de patrocinio no publicadas' },
      status: 'pending',
      sourceIds: [],
      method: null,
      note: null,
      reviewer: REVIEWER,
      reviewedAt: VERIFIED_AT,
      previousRevisionId: null,
    },
    {
      contractVersion: '1',
      id: 'clm-summit-access-r1',
      claimId: 'clm-summit-access',
      subject: { type: 'edition', editionId: 'ed-sf-dev-summit-2027' },
      attribute: 'access',
      value: { kind: 'text', text: 'Registro abierto según el listado' },
      status: 'observed',
      sourceIds: ['src-luma-dev-summit'],
      method: 'manual_curation',
      note: null,
      reviewer: REVIEWER,
      reviewedAt: VERIFIED_AT,
      previousRevisionId: null,
    },
    {
      contractVersion: '1',
      id: 'clm-mlnight-access-r1',
      claimId: 'clm-mlnight-access',
      subject: { type: 'edition', editionId: 'ed-ml-night-2026' },
      attribute: 'access',
      value: { kind: 'pending', note: 'el listado no declara si el registro es abierto o por invitación' },
      status: 'pending',
      sourceIds: [],
      method: null,
      note: null,
      reviewer: REVIEWER,
      reviewedAt: VERIFIED_AT,
      previousRevisionId: null,
    },
  ],
};
